### ISSUE TITLE
Remove binary files

### ISSUE THREAD

**Issue by kkweon** [nicewook/corona-visual-server#12]
- bin/corona-visual-server
- corona-visual-server.exe

These two files should be completely removed from the history as it takes the large amount of space.

- How to guide: https://docs.github.com/en/github/authenticating-to-github/removing-sensitive-data-from-a-repository

**Comment by nicewook** [comment]
Thanks! I will check it soon

**Comment by nicewook** [comment]
I encoutered similar case sometimes. what is the best procedure to remove files? 
for example, 
1) remove file and file history on local git
2) then git push?

**Comment by nicewook** [comment]
I think this could be an answer
https://itnext.io/how-to-remove-sensitive-files-from-github-commit-history-638a3f291f74

**Comment by nicewook** [comment]
Done with the link above
