### ISSUE TITLE
Remove vendor directory and instead set up a CI to find out if the project is buildable

### ISSUE THREAD

**Issue by kkweon** [nicewook/corona-visual-server#3]
The main reason is that it creates a lot of noises when linting the project when dependencies have bad code smells.
Otherwise, you have to specify which directory you want to include/exclude which is not ideal.

See https://stackoverflow.com/q/47346607 for more information why this is not the best practice.

**Comment by nicewook** [comment]
I see your point of lint things. I have to admit adding vendor folder using `go mod vendor` shows some strange action on changed files, etc. 
But coud you check the url https://www.ardanlabs.com/blog/2020/04/modules-06-vendoring.html ? It says that there's also some pros of `vendor`. I'm not insist to use vendor, but still I am confused which is the better.

**Comment by nicewook** [comment]
```
These are other benefits of vendoring:

If dependencies are removed from the VCS or somehow proxy servers lose modules, you are covered.
Upgrading dependencies can be seen by running diffs and you maintain a history.
You will have the ability to trace and debug your dependencies and test changes if necessary.
Once you run a go mod tidy and go mod vendor your changes will be replaced.
```

**Comment by kkweon** [comment]
I respect your decision, so please feel free to close if you disagree. 

I'm not saying there's no benefit of vendoring. 

If necessary, I can always run go vendor for one time job.

It's about commiting vendor or not. So, the only benefits are:

- You don't lose dependencies when they are removed.
  -   This can be a valid point for some projects. But, most of times, I want to know if my dependencies are completely removed as early as I can so that I can update.
- You see diff/changes in the dependencies
  - This is just a lot of noises. You don't want to see internal changes in all dependencies. You lost the history of why it happened. Software Design is all about abstraction.

**Comment by nicewook** [comment]
I do not disagree. I just want to know which is the better. 
I think I'm better to remove `vendor` for now. with having question in my mind. :-)

**Comment by kkweon** [comment]
제가 PR 에서 라이브러리 하나만 추가했어도 파일이 수십에서 수백가지 추가됬어서 리뷰가 불가능한 상황이었을 것입니다 😆  질문 주세요.

**Comment by nicewook** [comment]
짬날때 vendor 날리겠습니당
